# Generated by Django 2.2.1 on 2019-06-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
