# Generated by Django 2.2.1 on 2019-06-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
